services:
  petshop-db:
    image: mysql:8.4
    container_name: petshop-banco
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/petshop.sql:/docker-entrypoint-initdb.d/petshop.sql:ro
  petshop-api:
    build: ./backend
    image: petshop-api-imagem
    container_name: petshop-api-container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=petshop-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - petshop-db
  petshop-telinha:
    build: ./frontend
    image: petshop-front-imagem
    container_name: petshop-front-container
    ports:
      - "5173:5173"
    depends_on:
      - petshop-api

volumes:
  db_data:
